import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { EMBED_COMPONENTS } from './embed-components';
import { getLiveCalculators } from './calculators';

/**
 * R7D1 coverage — the embed manifest (component identity ONLY) must match the live
 * registry EXACTLY, and each generated page must be a LITERAL static import of one
 * island whose ROUTE is derived from the registry category (R7D1.1). The registry
 * stays the single authority on the live set + categories; the manifest carries no
 * category/title/status, so there is no duplicated projection to drift.
 */
const live = getLiveCalculators();
const liveSlugs = new Set(live.map((c) => c.slug));
const categoryOf = new Map(live.map((c) => [c.slug, c.category] as const));
const entries = Object.entries(EMBED_COMPONENTS);

describe('embed-components ↔ registry coverage', () => {
  it('has exactly one entry per LIVE calculator — no missing, no extra', () => {
    for (const c of live) expect(EMBED_COMPONENTS[c.slug], `missing embed entry for ${c.slug}`).toBeTruthy();
    for (const [slug] of entries) expect(liveSlugs.has(slug), `embed entry for non-live "${slug}"`).toBe(true);
    expect(entries.length).toBe(live.length);
  });

  it('carries component identity ONLY — no duplicated category/title/status projection', () => {
    for (const [slug, def] of entries) {
      expect(Object.keys(def).sort(), `${slug} keys`).toEqual(def.props ? ['componentPath', 'props'] : ['componentPath']);
    }
  });

  it('every componentPath resolves to a real file', () => {
    for (const [slug, def] of entries) {
      const disk = def.componentPath.replace(/^@components\//, 'src/components/');
      expect(existsSync(resolve(disk)), `${slug}: ${def.componentPath} missing`).toBe(true);
    }
  });

  it('props are serializable and cover the documented special cases only', () => {
    for (const [, def] of entries) {
      if (def.props) for (const v of Object.values(def.props)) expect(['string', 'number', 'boolean']).toContain(typeof v);
    }
    // No prop is left in the fleet: standard-deviation now has its own island rather than a
    // configured StatisticsCalculator, so component identity alone names every embed.
    for (const [slug, def] of entries) expect(def.props, `${slug} should carry no props`).toBeUndefined();
    expect(EMBED_COMPONENTS['standard-deviation-calculator'].componentPath).toBe(
      '@components/islands/StandardDeviationCalculator.astro',
    );
    expect(EMBED_COMPONENTS['statistics-calculator'].componentPath).toBe(
      '@components/islands/StatisticsCalculator.astro',
    );
    expect(EMBED_COMPONENTS['scientific-calculator'].componentPath).toBe(
      '@components/calc/ScientificCalculatorEmbed.astro',
    );
    expect(EMBED_COMPONENTS['password-generator'].componentPath).toBe(
      '@components/islands/PasswordGeneratorCalculator.astro',
    );
  });

  it('produces no duplicate routes (route category comes from the registry)', () => {
    const routes = entries.map(([slug]) => `${categoryOf.get(slug)}/${slug}`);
    expect(new Set(routes).size).toBe(routes.length);
  });

  it('the map keys are sorted (deterministic generation input)', () => {
    const keys = entries.map(([s]) => s);
    expect(keys).toEqual([...keys].sort());
  });
});

describe('generated embed pages are literal static imports (contract)', () => {
  it('each page: one literal island import + shared shell + registry-derived route + expected props + no dynamic lookup', () => {
    for (const [slug, def] of entries) {
      const category = categoryOf.get(slug)!;
      const p = resolve('src/pages/embed', category, `${slug}.astro`);
      expect(existsSync(p), `missing generated page for ${slug}`).toBe(true);
      const src = readFileSync(p, 'utf8');
      // exactly one literal calculator-component import
      const islandImports = [...src.matchAll(/import Island from '([^']+)';/g)];
      expect(islandImports.length, `${slug} island imports`).toBe(1);
      expect(islandImports[0][1]).toBe(def.componentPath);
      // one shared EmbedPageShell import + registry-derived route
      expect(src).toContain("import EmbedPageShell from '@layouts/EmbedPageShell.astro'");
      expect(src).toContain(`getCalculator('${category}', '${slug}')`);
      // generated warning header
      expect(src).toContain('AUTO-GENERATED by scripts/gen-embed-pages.mjs');
      // no map / glob / dynamic lookup / runtime component request / legacy renderer
      expect(src).not.toMatch(/import\.meta\.glob/);
      expect(src).not.toMatch(/ISLANDS\[|IslandBySlug/);
      expect(src).not.toMatch(/await import\(/);
      // deterministic: LF newlines only, trailing newline
      expect(src.includes('\r')).toBe(false);
      expect(src.endsWith('\n')).toBe(true);
      if (def.props) {
        for (const [k, v] of Object.entries(def.props)) {
          const attr = typeof v === 'string' ? `${k}=${JSON.stringify(v)}` : `${k}={${JSON.stringify(v)}}`;
          expect(src, `${slug} should render prop ${k}`).toContain(attr);
        }
      }
    }
  });
});
